# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :title.html
relative_permalinks: true

# Setup
title:               fka blog
tagline:             'development journal'
description:         'JavaScript and front-end writings by Fatih Kadir Akın. Posts may be in English or Turkish'
url:                 http://f.github.io
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Fatih Kadir Akın
  url:               https://twitter.com/fkadev
  email:             fatihkadirakin@gmail.com

# Custom vars
version:             1.0.0
