# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               fka blog
tagline:             'development journal. (posts may be in English or Turkish)'
description:         'JavaScript and front-end writings by Fatih Kadir Akın.'
url:                 http://f.github.io
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Fatih Kadir Akın
  url:               https://twitter.com/fkadev
  email:             fatihkadirakin@gmail.com

# Custom vars
version:             1.0.0
